### ISSUE TITLE
Error when starting the Accounts API

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/accounts-docker#3] opened 2017-05-22 08:05 UTC
The API component does not launch cleanly, which seems to be related to this issue: <http://stackoverflow.com/questions/37273621/fail-to-start-jax-rs-service-on-wildfly-swarm>

The log (given by `docker-compose logs -f api`):

`2017-05-20 09:27:18,999 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.`

**Comment by mskyttner** [comment] 2017-08-30 13:02
I have been testing, using the development branch and "make" I get a successful build and "make up" launches most services but not the API service.

See the log using `docker-compose logs api` for details, from the stack trace I found this error:

`Caused by: javax.ejb.EJBException: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized`

Not sure what causes it. Any ideas?

**Comment by mikkohei13** [comment] 2017-09-11 12:01
Caused by no initial user set up in Keycloak. Fixed with c07781446928504ff7dccf1aaa017417791dca53

**Closed by mikkohei13** 2017-09-11 12:01 UTC
